//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GregInterviewWinforms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffID { get; set; }
        public int StaffTypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int StaffStatusID { get; set; }
        public string MiddleInitial { get; set; }
        public string PhHome { get; set; }
        public string PhCell { get; set; }
        public string PhExt { get; set; }
        public string IRD { get; set; }
        public int StaffTitleID { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual StaffStatu StaffStatu { get; set; }
        public virtual StaffType StaffType { get; set; }
        public virtual StaffTitle StaffTitle { get; set; }
    }
}
